const crops=[
{name:'Tomato',icon:'🍅',months:'Aug–Jan',depth:'5 mm',spacing:'40–60 cm',harvest:'10–14 weeks',sun:'Full sun',tip:'Plant after frost risk has passed. Stake tall varieties early.'},
{name:'Carrot',icon:'🥕',months:'Most of year',depth:'5 mm',spacing:'3–5 cm',harvest:'10–16 weeks',sun:'Full sun',tip:'Sow directly into loose, stone-free soil. Keep seedbed moist.'},
{name:'Lettuce',icon:'🥬',months:'Most of year',depth:'3 mm',spacing:'20–30 cm',harvest:'6–10 weeks',sun:'Sun / part shade',tip:'Use afternoon shade in hot weather and succession sow every few weeks.'},
{name:'Potato',icon:'🥔',months:'Jul–Dec',depth:'10–15 cm',spacing:'30–40 cm',harvest:'12–20 weeks',sun:'Full sun',tip:'Hill soil around stems as plants grow to protect developing tubers.'},
{name:'Pumpkin',icon:'🎃',months:'Sep–Dec',depth:'2–3 cm',spacing:'1–2 m',harvest:'16–20 weeks',sun:'Full sun',tip:'Give vines plenty of room and water deeply during flowering and fruit set.'},
{name:'Beans',icon:'🫘',months:'Sep–Feb',depth:'2–3 cm',spacing:'10–15 cm',harvest:'8–12 weeks',sun:'Full sun',tip:'Sow directly. Provide a trellis for climbing varieties.'},
{name:'Peas',icon:'🫛',months:'Feb–Aug',depth:'2–4 cm',spacing:'5–10 cm',harvest:'10–14 weeks',sun:'Full sun',tip:'Best in cool conditions. Support climbing plants with mesh or stakes.'},
{name:'Beetroot',icon:'🌱',months:'Most of year',depth:'1–2 cm',spacing:'8–12 cm',harvest:'8–12 weeks',sun:'Full sun',tip:'Soak seed clusters briefly before sowing and thin seedlings after emergence.'},
{name:'Zucchini',icon:'🥒',months:'Sep–Jan',depth:'2 cm',spacing:'70–100 cm',harvest:'7–10 weeks',sun:'Full sun',tip:'Pick fruit young and regularly to keep plants producing.'},
{name:'Corn',icon:'🌽',months:'Sep–Jan',depth:'2–4 cm',spacing:'25–30 cm',harvest:'12–16 weeks',sun:'Full sun',tip:'Plant in blocks rather than a single row for better wind pollination.'},
{name:'Onion',icon:'🧅',months:'Mar–Sep',depth:'5–10 mm',spacing:'8–12 cm',harvest:'20–30 weeks',sun:'Full sun',tip:'Keep beds weed-free; onions compete poorly while young.'},
{name:'Broccoli',icon:'🥦',months:'Feb–Jun',depth:'5 mm',spacing:'40–50 cm',harvest:'12–18 weeks',sun:'Full sun',tip:'Grow through cooler months and protect young plants from cabbage moth.'}
];
const $=s=>document.querySelector(s);const grid=$('#cropGrid');
function render(list=crops){grid.innerHTML=list.map((c,i)=>`<article class="crop-card" data-name="${c.name}"><div class="crop-icon">${c.icon}</div><h3>${c.name}</h3><p>Sow: ${c.months}</p><p>Depth: <strong>${c.depth}</strong></p><span class="tag">${c.harvest}</span></article>`).join('');document.querySelectorAll('.crop-card').forEach(x=>x.onclick=()=>openCrop(x.dataset.name));}
function openCrop(name){const c=crops.find(x=>x.name===name);$('#cropDetails').innerHTML=`<div class="crop-icon">${c.icon}</div><p class="eyebrow">Growing guide</p><h2>${c.name}</h2><div class="detail-grid"><div class="detail"><small>Best sowing</small><br><strong>${c.months}</strong></div><div class="detail"><small>Sowing depth</small><br><strong>${c.depth}</strong></div><div class="detail"><small>Spacing</small><br><strong>${c.spacing}</strong></div><div class="detail"><small>Harvest</small><br><strong>${c.harvest}</strong></div><div class="detail"><small>Light</small><br><strong>${c.sun}</strong></div></div><p>${c.tip}</p><button class="add-btn" onclick="saveCrop('${c.name}')">Add to my garden</button>`;$('#cropDialog').showModal();}
window.saveCrop=name=>{const saved=new Set(JSON.parse(localStorage.getItem('garden')||'[]'));saved.add(name);localStorage.setItem('garden',JSON.stringify([...saved]));renderGarden();$('#cropDialog').close();};
function renderGarden(){const names=JSON.parse(localStorage.getItem('garden')||'[]');const box=$('#savedGarden');box.innerHTML=names.map(n=>{const c=crops.find(x=>x.name===n);return `<article class="crop-card" onclick="openCrop('${c.name}')"><div class="crop-icon">${c.icon}</div><h3>${c.name}</h3><p>Depth: ${c.depth}</p><span class="tag">${c.harvest}</span></article>`}).join('');$('#emptyGarden').hidden=names.length>0;}
$('.tabs').onclick=e=>{if(!e.target.matches('.tab'))return;document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#'+e.target.dataset.tab).classList.add('active');};
$('#searchInput').oninput=e=>render(crops.filter(c=>c.name.toLowerCase().includes(e.target.value.toLowerCase())));
$('#closeDialog').onclick=()=>$('#cropDialog').close();
$('#plantPhoto').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#preview').src=URL.createObjectURL(f);$('#preview').hidden=false;$('#photoStatus').textContent='Photo ready. Plant diagnosis is the next feature to connect.';};
$('#locationBtn').onclick=()=>{if(!navigator.geolocation){$('#regionLabel').textContent='Location unavailable';return;}$('#locationBtn').textContent='Locating…';navigator.geolocation.getCurrentPosition(()=>{$('#regionLabel').textContent='Local Australian garden';$('#locationBtn').textContent='Location set';},()=>{$('#locationBtn').textContent='Try location again';});};
const m=new Date().getMonth()+1;$('#seasonLabel').textContent=m>=9&&m<=11?'Spring planting season':m===12||m<=2?'Summer growing season':m>=3&&m<=5?'Autumn growing season':'Winter growing season';render();renderGarden();
